# Docker compose file to bring up app and test containers
# See http://docs.microsoft.com/azure/devops/pipelines/languages/docker for more information

  build: .
  dockerfile: docs/Dockerfile.test
  links:
    - web

  build: .
  dockerfile: Dockerfile